FROM devopseasylearning2021/challenger:postgres-10.0
MAINTAINER EK TECH SOFTWARE SOLUTION

WORKDIR /

COPY init-yelb-db.sh /docker-entrypoint-initdb.d/init-yelb-db.sh

ENV POSTGRES_PASSWORD=postgres_password


