apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.labels.app2 }}
  labels:
    app: {{ .Values.labels.app2 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.labels.app2 }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.autoscaling.name }}
      target:
        type: {{ .Values.autoscaling.type }}
        averageUtilization: {{ .Values.autoscaling.averageUtilization }}