apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f dep.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 8080
  selector:
    io.kompose.service: adminer
status:
  loadBalancer: {}
