apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-svc
  labels:
        app: {{ .Values.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
        app: {{ .Values.labels.app }}

